<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>$(ShamisenCurrentTargetFramework)</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
  <Import Project="../TargetFrameworks.targets" />
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.5" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.5" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
        <PackageReference Include="ReactiveProperty" Version="9.7.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shamisen.IO.OpenTK\Shamisen.IO.OpenTK.csproj" />
        <ProjectReference Include="..\Shamisen\Shamisen.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
</Project>
