<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>$(ShamisenCurrentTargetFramework)</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="ReactiveProperty" Version="9.8.0" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shamisen.IO.OpenTK\Shamisen.IO.OpenTK.csproj" />
        <ProjectReference Include="..\Shamisen\Shamisen.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
</Project>
