<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>NU1605;CS1591;CS1574;CS8625;CS8602;CS8603;CS8618</WarningsAsErrors>
        <Authors>MineCake1.4.7</Authors>
        <Copyright>Copyright 2022 MineCake1.4.7</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/MineCake147E/Shamisen</PackageProjectUrl>
        <RepositoryUrl>https://github.com/MineCake147E/Shamisen.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <VersionPrefix>0.1.0</VersionPrefix>
        <VersionSuffix>alpha.0.7.0</VersionSuffix>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageOutputPath>$(SolutionDir)Packages</PackageOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
        <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile></DocumentationFile>
    </PropertyGroup>
  <ItemGroup>
    <TextTemplate Include="./**/*.tt" />
    <Compile Update="@(TextTemplate->'%(RelativeDir)%(Filename).cs')">
      <AutoGen>True</AutoGen>
      <DependentUpon>%(Filename).tt</DependentUpon>
    </Compile>
    <None Include="@(TextTemplate)">
      <LastGenOutput>%(Filename).cs</LastGenOutput>
    </None>
    <UpToDateCheckBuilt Include="@(TextTemplate->'%(RelativeDir)%(Filename).cs')" Original="@(TextTemplate)" />
  </ItemGroup>
  <Target Name="TextTemplateTransform" BeforeTargets="BeforeBuild" Inputs="@(TextTemplate)" Outputs="@(TextTemplate->'%(RelativeDir)%(Filename).cs')">
    <ItemGroup>
      <T4GFirstBuild Include="@(TextTemplate->'%(RelativeDir)%(Filename).cs')" />
      <T4Generated Include="@(T4GFirstBuild->'%(Identity)')" Condition="!Exists('%(FullPath)')" />
      <Compile Include="@(T4GFirstBuild->'%(Identity)')" Condition="!Exists('%(FullPath)')">
        <AutoGen>True</AutoGen>
        <DependentUpon>%(Filename).tt</DependentUpon>
      </Compile>
    </ItemGroup>
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet t4 -p:Configuration='$(Configuration)' %(TextTemplate.Identity)" />
  </Target>
  <Target Name="TextTemplateClean" AfterTargets="Clean">
    <Delete Files="@(TextTemplate->'%(RelativeDir)%(Filename).cs')" />
  </Target>
</Project>
