// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// Generated at 2021/03/12 18:40:52.563072
// </auto-generated>
using System;
using Shamisen;

namespace Shamisen.Codecs.Waveform
{
    /// <summary>
    /// Represents a subchunk ID for waveform "LIST" chunk in Little Endian.
    /// </summary>
    public enum InfoSubChunkId : uint
    {
        /// <summary>
        /// The Archival Location subchunk "IARL" read in Little Endian.
        /// </summary>
        ArchivalLocation = 1280459081,
        /// <summary>
        /// The Artist subchunk "IART" read in Little Endian.
        /// </summary>
        Artist = 1414676809,
        /// <summary>
        /// The Commissioned subchunk "ICMS" read in Little Endian.
        /// </summary>
        Commissioned = 1397572425,
        /// <summary>
        /// The Comments subchunk "ICMT" read in Little Endian.
        /// </summary>
        Comments = 1414349641,
        /// <summary>
        /// The Copyright subchunk "ICOP" read in Little Endian.
        /// </summary>
        Copyright = 1347371849,
        /// <summary>
        /// The Creation Date subchunk "ICRD" read in Little Endian.
        /// </summary>
        CreationDate = 1146241865,
        /// <summary>
        /// The Cropped subchunk "ICRP" read in Little Endian.
        /// </summary>
        Cropped = 1347568457,
        /// <summary>
        /// The Dimensions subchunk "IDIM" read in Little Endian.
        /// </summary>
        Dimensions = 1296647241,
        /// <summary>
        /// The Dots Per Inch subchunk "IDPI" read in Little Endian.
        /// </summary>
        DotsPerInch = 1229997129,
        /// <summary>
        /// The Engineer subchunk "IENG" read in Little Endian.
        /// </summary>
        Engineer = 1196311881,
        /// <summary>
        /// The Genre subchunk "IGNR" read in Little Endian.
        /// </summary>
        Genre = 1380861769,
        /// <summary>
        /// The Keywords subchunk "IKEY" read in Little Endian.
        /// </summary>
        Keywords = 1497713481,
        /// <summary>
        /// The Lightness subchunk "ILGT" read in Little Endian.
        /// </summary>
        Lightness = 1413958729,
        /// <summary>
        /// The Medium subchunk "IMED" read in Little Endian.
        /// </summary>
        Medium = 1145392457,
        /// <summary>
        /// The Name subchunk "INAM" read in Little Endian.
        /// </summary>
        Name = 1296125513,
        /// <summary>
        /// The Palette Setting subchunk "IPLT" read in Little Endian.
        /// </summary>
        PaletteSetting = 1414287433,
        /// <summary>
        /// The Product subchunk "IPRD" read in Little Endian.
        /// </summary>
        Product = 1146245193,
        /// <summary>
        /// The Subject subchunk "ISBJ" read in Little Endian.
        /// </summary>
        Subject = 1245860681,
        /// <summary>
        /// The Software subchunk "ISFT" read in Little Endian.
        /// </summary>
        Software = 1413894985,
        /// <summary>
        /// The Sharpness subchunk "ISHP" read in Little Endian.
        /// </summary>
        Sharpness = 1346917193,
        /// <summary>
        /// The Source subchunk "ISRC" read in Little Endian.
        /// </summary>
        Source = 1129468745,
        /// <summary>
        /// The SourceForm subchunk "ISRF" read in Little Endian.
        /// </summary>
        SourceForm = 1179800393,
        /// <summary>
        /// The Technician subchunk "ITCH" read in Little Endian.
        /// </summary>
        Technician = 1212372041,
    }
}
