// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System;
using MonoAudio;

namespace MonoAudio.Codecs.Waveform
{
    /// <summary>
    /// Represents a subchunk ID for waveform "LIST" chunk in Little Endian.
    /// </summary>
    public enum InfoSubChunkId : uint
    {
        /// <summary>
        /// The Archival Location subchunk "IARL" read in Little Endian.
        /// </summary>
        ArchivalLocation = 1414744396,
        /// <summary>
        /// The Artist subchunk "IART" read in Little Endian.
        /// </summary>
        Artist = 1414744396,
        /// <summary>
        /// The Commissioned subchunk "ICMS" read in Little Endian.
        /// </summary>
        Commissioned = 1414744396,
        /// <summary>
        /// The Comments subchunk "ICMT" read in Little Endian.
        /// </summary>
        Comments = 1414744396,
        /// <summary>
        /// The Copyright subchunk "ICOP" read in Little Endian.
        /// </summary>
        Copyright = 1414744396,
        /// <summary>
        /// The Creation Date subchunk "ICRD" read in Little Endian.
        /// </summary>
        CreationDate = 1414744396,
        /// <summary>
        /// The Cropped subchunk "ICRP" read in Little Endian.
        /// </summary>
        Cropped = 1414744396,
        /// <summary>
        /// The Dimensions subchunk "IDIM" read in Little Endian.
        /// </summary>
        Dimensions = 1414744396,
        /// <summary>
        /// The Dots Per Inch subchunk "IDPI" read in Little Endian.
        /// </summary>
        DotsPerInch = 1414744396,
        /// <summary>
        /// The Engineer subchunk "IENG" read in Little Endian.
        /// </summary>
        Engineer = 1414744396,
        /// <summary>
        /// The Genre subchunk "IGNR" read in Little Endian.
        /// </summary>
        Genre = 1414744396,
        /// <summary>
        /// The Keywords subchunk "IKEY" read in Little Endian.
        /// </summary>
        Keywords = 1414744396,
        /// <summary>
        /// The Lightness subchunk "ILGT" read in Little Endian.
        /// </summary>
        Lightness = 1414744396,
        /// <summary>
        /// The Medium subchunk "IMED" read in Little Endian.
        /// </summary>
        Medium = 1414744396,
        /// <summary>
        /// The Name subchunk "INAM" read in Little Endian.
        /// </summary>
        Name = 1414744396,
        /// <summary>
        /// The Palette Setting subchunk "IPLT" read in Little Endian.
        /// </summary>
        PaletteSetting = 1414744396,
        /// <summary>
        /// The Product subchunk "IPRD" read in Little Endian.
        /// </summary>
        Product = 1414744396,
        /// <summary>
        /// The Subject subchunk "ISBJ" read in Little Endian.
        /// </summary>
        Subject = 1414744396,
        /// <summary>
        /// The Software subchunk "ISFT" read in Little Endian.
        /// </summary>
        Software = 1414744396,
        /// <summary>
        /// The Sharpness subchunk "ISHP" read in Little Endian.
        /// </summary>
        Sharpness = 1414744396,
        /// <summary>
        /// The Source subchunk "ISRC" read in Little Endian.
        /// </summary>
        Source = 1414744396,
        /// <summary>
        /// The SourceForm subchunk "ISRF" read in Little Endian.
        /// </summary>
        SourceForm = 1414744396,
        /// <summary>
        /// The Technician subchunk "ITCH" read in Little Endian.
        /// </summary>
        Technician = 1414744396,
    }
}
