// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System;
using MonoAudio;

namespace MonoAudio.Codecs.Waveform
{
    /// <summary>
    /// Represents a sub format for <see cref="ExtensibleWaveFormat.SubFormat"/>.
    /// </summary>
    public static partial class WaveformSubFormats
    {
        /// <summary>
        /// Unknown format
        /// </summary>
        public static readonly Guid Unknown = AudioEncoding.Unknown.ToGuid();
        /// <summary>
        /// Microsoft PCM Format
        /// </summary>
        public static readonly Guid LinearPcm = AudioEncoding.LinearPcm.ToGuid();
        /// <summary>
        /// Microsoft ADPCM Format
        /// </summary>
        public static readonly Guid MsAdpcm = AudioEncoding.MsAdpcm.ToGuid();
        /// <summary>
        /// IEEE 754 Single Precision Floating-Point Number
        /// </summary>
        public static readonly Guid IeeeFloat = AudioEncoding.IeeeFloat.ToGuid();
        /// <summary>
        /// Vector sum excited linear prediction Compaq Computer Corporation
        /// </summary>
        public static readonly Guid Vselp = AudioEncoding.Vselp.ToGuid();
        /// <summary>
        /// IBM Corporation
        /// </summary>
        public static readonly Guid IbmCvsd = AudioEncoding.IbmCvsd.ToGuid();
        /// <summary>
        /// A-law format by Microsoft Corporation
        /// </summary>
        public static readonly Guid Alaw = AudioEncoding.Alaw.ToGuid();
        /// <summary>
        /// μ-law format by Microsoft Corporation
        /// </summary>
        public static readonly Guid Mulaw = AudioEncoding.Mulaw.ToGuid();
        /// <summary>
        /// OKI ADPCM
        /// </summary>
        public static readonly Guid OkiAdpcm = AudioEncoding.OkiAdpcm.ToGuid();
        /// <summary>
        /// Intel Corporation ADPCM
        /// </summary>
        public static readonly Guid ImaAdpcm = AudioEncoding.ImaAdpcm.ToGuid();
        /// <summary>
        /// Videologic ADPCM
        /// </summary>
        public static readonly Guid MediaspaceAdpcm = AudioEncoding.MediaspaceAdpcm.ToGuid();
        /// <summary>
        /// Sierra Semiconductor Corp
        /// </summary>
        public static readonly Guid SierraAdpcm = AudioEncoding.SierraAdpcm.ToGuid();
        /// <summary>
        /// Antex Electronics Corporation
        /// </summary>
        public static readonly Guid G723Adpcm = AudioEncoding.G723Adpcm.ToGuid();
        /// <summary>
        /// DSP Solutions, Inc.
        /// </summary>
        public static readonly Guid Digistd = AudioEncoding.Digistd.ToGuid();
        /// <summary>
        /// DSP Solutions, Inc.
        /// </summary>
        public static readonly Guid Digifix = AudioEncoding.Digifix.ToGuid();
        /// <summary>
        /// Dialogic Corporation
        /// </summary>
        public static readonly Guid DialogicOkiAdpcm = AudioEncoding.DialogicOkiAdpcm.ToGuid();
        /// <summary>
        /// Media Vision, Inc.
        /// </summary>
        public static readonly Guid MediavisionAdpcm = AudioEncoding.MediavisionAdpcm.ToGuid();
        /// <summary>
        /// Hewlett-Packard Company
        /// </summary>
        public static readonly Guid CuCodec = AudioEncoding.CuCodec.ToGuid();
        /// <summary>
        /// Yamaha Corporation of America
        /// </summary>
        public static readonly Guid YamahaAdpcm = AudioEncoding.YamahaAdpcm.ToGuid();
        /// <summary>
        /// Speech Compression
        /// </summary>
        public static readonly Guid Sonarc = AudioEncoding.Sonarc.ToGuid();
        /// <summary>
        /// DSP Group, Inc
        /// </summary>
        public static readonly Guid DspgroupTruespeech = AudioEncoding.DspgroupTruespeech.ToGuid();
        /// <summary>
        /// Echo Speech Corporation
        /// </summary>
        public static readonly Guid Echosc1 = AudioEncoding.Echosc1.ToGuid();
        /// <summary>
        /// Audiofile, Inc.
        /// </summary>
        public static readonly Guid AudiofileAf36 = AudioEncoding.AudiofileAf36.ToGuid();
        /// <summary>
        /// Audio Processing Technology
        /// </summary>
        public static readonly Guid Aptx = AudioEncoding.Aptx.ToGuid();
        /// <summary>
        /// Audiofile, Inc.
        /// </summary>
        public static readonly Guid AudiofileAf10 = AudioEncoding.AudiofileAf10.ToGuid();
        /// <summary>
        /// Aculab plc
        /// </summary>
        public static readonly Guid Prosody1612 = AudioEncoding.Prosody1612.ToGuid();
        /// <summary>
        /// Merging Technologies S.A.
        /// </summary>
        public static readonly Guid Lrc = AudioEncoding.Lrc.ToGuid();
        /// <summary>
        /// Dolby Laboratories
        /// </summary>
        public static readonly Guid DolbyAc2 = AudioEncoding.DolbyAc2.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid Gsm610 = AudioEncoding.Gsm610.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid Msnaudio = AudioEncoding.Msnaudio.ToGuid();
        /// <summary>
        /// Antex Electronics Corporation
        /// </summary>
        public static readonly Guid AntexAdpcme = AudioEncoding.AntexAdpcme.ToGuid();
        /// <summary>
        /// Control Resources Limited
        /// </summary>
        public static readonly Guid ControlResVqlpc = AudioEncoding.ControlResVqlpc.ToGuid();
        /// <summary>
        /// DSP Solutions, Inc.
        /// </summary>
        public static readonly Guid Digireal = AudioEncoding.Digireal.ToGuid();
        /// <summary>
        /// DSP Solutions, Inc.
        /// </summary>
        public static readonly Guid Digiadpcm = AudioEncoding.Digiadpcm.ToGuid();
        /// <summary>
        /// Control Resources Limited
        /// </summary>
        public static readonly Guid ControlResCr10 = AudioEncoding.ControlResCr10.ToGuid();
        /// <summary>
        /// Natural MicroSystems
        /// </summary>
        public static readonly Guid NmsVbxadpcm = AudioEncoding.NmsVbxadpcm.ToGuid();
        /// <summary>
        /// Roland
        /// </summary>
        public static readonly Guid RolandRdac = AudioEncoding.RolandRdac.ToGuid();
        /// <summary>
        /// Echo Speech Corporation
        /// </summary>
        public static readonly Guid Echosc3 = AudioEncoding.Echosc3.ToGuid();
        /// <summary>
        /// Rockwell International
        /// </summary>
        public static readonly Guid RockwellAdpcm = AudioEncoding.RockwellAdpcm.ToGuid();
        /// <summary>
        /// Rockwell International
        /// </summary>
        public static readonly Guid RockwellDigitalk = AudioEncoding.RockwellDigitalk.ToGuid();
        /// <summary>
        /// Xebec Multimedia Solutions Limited
        /// </summary>
        public static readonly Guid Xebec = AudioEncoding.Xebec.ToGuid();
        /// <summary>
        /// Antex Electronics Corporation
        /// </summary>
        public static readonly Guid G721Adpcm = AudioEncoding.G721Adpcm.ToGuid();
        /// <summary>
        /// Antex Electronics Corporation
        /// </summary>
        public static readonly Guid G728Celp = AudioEncoding.G728Celp.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid Msg723 = AudioEncoding.Msg723.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid Mpeg = AudioEncoding.Mpeg.ToGuid();
        /// <summary>
        /// InSoft Inc.
        /// </summary>
        public static readonly Guid Rt24 = AudioEncoding.Rt24.ToGuid();
        /// <summary>
        /// InSoft Inc.
        /// </summary>
        public static readonly Guid Pac = AudioEncoding.Pac.ToGuid();
        /// <summary>
        /// MPEG 3 Layer 1
        /// </summary>
        public static readonly Guid Mpeglayer3 = AudioEncoding.Mpeglayer3.ToGuid();
        /// <summary>
        /// Lucent Technologies
        /// </summary>
        public static readonly Guid LucentG723 = AudioEncoding.LucentG723.ToGuid();
        /// <summary>
        /// Cirrus Logic
        /// </summary>
        public static readonly Guid Cirrus = AudioEncoding.Cirrus.ToGuid();
        /// <summary>
        /// ESS Technology
        /// </summary>
        public static readonly Guid Espcm = AudioEncoding.Espcm.ToGuid();
        /// <summary>
        /// Voxware Inc
        /// </summary>
        public static readonly Guid Voxware = AudioEncoding.Voxware.ToGuid();
        /// <summary>
        /// Canopus, Co., Ltd.
        /// </summary>
        public static readonly Guid CanopusAtrac = AudioEncoding.CanopusAtrac.ToGuid();
        /// <summary>
        /// APICOM
        /// </summary>
        public static readonly Guid G726Adpcm = AudioEncoding.G726Adpcm.ToGuid();
        /// <summary>
        /// APICOM
        /// </summary>
        public static readonly Guid G722Adpcm = AudioEncoding.G722Adpcm.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid Dsat = AudioEncoding.Dsat.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid DsatDisplay = AudioEncoding.DsatDisplay.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareByteAligned = AudioEncoding.VoxwareByteAligned.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareAc8 = AudioEncoding.VoxwareAc8.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareAc10 = AudioEncoding.VoxwareAc10.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareAc16 = AudioEncoding.VoxwareAc16.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareAc20 = AudioEncoding.VoxwareAc20.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareRt24 = AudioEncoding.VoxwareRt24.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareRt29 = AudioEncoding.VoxwareRt29.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareRt29hw = AudioEncoding.VoxwareRt29hw.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareVr12 = AudioEncoding.VoxwareVr12.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareVr18 = AudioEncoding.VoxwareVr18.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxwareTq40 = AudioEncoding.VoxwareTq40.ToGuid();
        /// <summary>
        /// Softsound, Ltd.
        /// </summary>
        public static readonly Guid Softsound = AudioEncoding.Softsound.ToGuid();
        /// <summary>
        /// Voxware Inc.
        /// </summary>
        public static readonly Guid VoxareTq60 = AudioEncoding.VoxareTq60.ToGuid();
        /// <summary>
        /// Microsoft Corporation
        /// </summary>
        public static readonly Guid Msrt24 = AudioEncoding.Msrt24.ToGuid();
        /// <summary>
        /// AT&amp;T Laboratories
        /// </summary>
        public static readonly Guid G729a = AudioEncoding.G729a.ToGuid();
        /// <summary>
        /// Motion Pixels
        /// </summary>
        public static readonly Guid MviMv12 = AudioEncoding.MviMv12.ToGuid();
        /// <summary>
        /// DataFusion Systems (Pty) (Ltd)
        /// </summary>
        public static readonly Guid DfG726 = AudioEncoding.DfG726.ToGuid();
        /// <summary>
        /// DataFusion Systems (Pty) (Ltd)
        /// </summary>
        public static readonly Guid DfGsm610 = AudioEncoding.DfGsm610.ToGuid();
        /// <summary>
        /// OnLive! Technologies, Inc.
        /// </summary>
        public static readonly Guid Onlive = AudioEncoding.Onlive.ToGuid();
        /// <summary>
        /// Siemens Business Communications Systems
        /// </summary>
        public static readonly Guid Sbc24 = AudioEncoding.Sbc24.ToGuid();
        /// <summary>
        /// Sonic Foundry
        /// </summary>
        public static readonly Guid DolbyAc3Spdif = AudioEncoding.DolbyAc3Spdif.ToGuid();
        /// <summary>
        /// ZyXEL Communications, Inc.
        /// </summary>
        public static readonly Guid ZyxelAdpcm = AudioEncoding.ZyxelAdpcm.ToGuid();
        /// <summary>
        /// Philips Speech Processing
        /// </summary>
        public static readonly Guid PhilipsLpcbb = AudioEncoding.PhilipsLpcbb.ToGuid();
        /// <summary>
        /// Studer Professional Audio AG
        /// </summary>
        public static readonly Guid Packed = AudioEncoding.Packed.ToGuid();
        /// <summary>
        /// Rhetorex, Inc.
        /// </summary>
        public static readonly Guid RhetorexAdpcm = AudioEncoding.RhetorexAdpcm.ToGuid();
        /// <summary>
        /// IBM mu-law format
        /// </summary>
        public static readonly Guid IbmMulaw = AudioEncoding.IbmMulaw.ToGuid();
        /// <summary>
        /// IBM a-law format
        /// </summary>
        public static readonly Guid IbmAlaw = AudioEncoding.IbmAlaw.ToGuid();
        /// <summary>
        /// IBM AVC Adaptive Differential PCM format
        /// </summary>
        public static readonly Guid Adpcm = AudioEncoding.Adpcm.ToGuid();
        /// <summary>
        /// Vivo Software
        /// </summary>
        public static readonly Guid VivoG723 = AudioEncoding.VivoG723.ToGuid();
        /// <summary>
        /// Vivo Software
        /// </summary>
        public static readonly Guid VivoSiren = AudioEncoding.VivoSiren.ToGuid();
        /// <summary>
        /// Digital Equipment Corporation
        /// </summary>
        public static readonly Guid DigitalG723 = AudioEncoding.DigitalG723.ToGuid();
        /// <summary>
        /// Creative Labs, Inc
        /// </summary>
        public static readonly Guid CreativeAdpcm = AudioEncoding.CreativeAdpcm.ToGuid();
        /// <summary>
        /// Creative Labs, Inc
        /// </summary>
        public static readonly Guid CreativeFastspeech8 = AudioEncoding.CreativeFastspeech8.ToGuid();
        /// <summary>
        /// Creative Labs, Inc
        /// </summary>
        public static readonly Guid CreativeFastspeech10 = AudioEncoding.CreativeFastspeech10.ToGuid();
        /// <summary>
        /// Quarterdeck Corporation
        /// </summary>
        public static readonly Guid Quarterdeck = AudioEncoding.Quarterdeck.ToGuid();
        /// <summary>
        /// Fujitsu Corporation
        /// </summary>
        public static readonly Guid FmTownsSnd = AudioEncoding.FmTownsSnd.ToGuid();
        /// <summary>
        /// Brooktree Corporation
        /// </summary>
        public static readonly Guid BzvDigital = AudioEncoding.BzvDigital.ToGuid();
        /// <summary>
        /// AT&amp;T Labs, Inc.
        /// </summary>
        public static readonly Guid VmeVmpcm = AudioEncoding.VmeVmpcm.ToGuid();
        /// <summary>
        /// Ing C. Olivetti &amp; C., S.p.A.
        /// </summary>
        public static readonly Guid Oligsm = AudioEncoding.Oligsm.ToGuid();
        /// <summary>
        /// Ing C. Olivetti &amp; C., S.p.A.
        /// </summary>
        public static readonly Guid Oliadpcm = AudioEncoding.Oliadpcm.ToGuid();
        /// <summary>
        /// Ing C. Olivetti &amp; C., S.p.A.
        /// </summary>
        public static readonly Guid Olicelp = AudioEncoding.Olicelp.ToGuid();
        /// <summary>
        /// Ing C. Olivetti &amp; C., S.p.A.
        /// </summary>
        public static readonly Guid Olisbc = AudioEncoding.Olisbc.ToGuid();
        /// <summary>
        /// Ing C. Olivetti &amp; C., S.p.A.
        /// </summary>
        public static readonly Guid Oliopr = AudioEncoding.Oliopr.ToGuid();
        /// <summary>
        /// Lernout &amp; Hauspie
        /// </summary>
        public static readonly Guid LhCodec = AudioEncoding.LhCodec.ToGuid();
        /// <summary>
        /// Norris Communications, Inc.
        /// </summary>
        public static readonly Guid Norris = AudioEncoding.Norris.ToGuid();
        /// <summary>
        /// AT&amp;T Labs, Inc.
        /// </summary>
        public static readonly Guid SoundspaceMusicompress = AudioEncoding.SoundspaceMusicompress.ToGuid();
        /// <summary>
        /// FAST Multimedia AG
        /// </summary>
        public static readonly Guid Dvm = AudioEncoding.Dvm.ToGuid();
        /// <summary>
        /// ?????
        /// </summary>
        public static readonly Guid InterwavVsc112 = AudioEncoding.InterwavVsc112.ToGuid();
    }
}
