
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Text;
using System.Threading.Tasks;

namespace Shamisen.Codecs.Flac.SubFrames
{
    public sealed partial class FlacLinearPredictionSubFrame
    {
        internal static partial class X86
        {
            internal static bool IsAvx512FVLSupported => Avx512F.IsSupported && Avx512F.VL.IsSupported;
            
            [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
            internal static void RestoreSignalAvx512FVL(in RestoreParameters parameters)
            {
                switch (parameters.PredictorOrder)
                {
                    case 1:
                        if (Unsafe.SizeOf<nint>() == sizeof(long) || (RuntimeFeature.IsDynamicCodeCompiled && parameters.MultiplyBitsRequired <= Unsafe.SizeOf<nint>() * 8 && parameters.AccumulatorBitsRequired <= Unsafe.SizeOf<nint>() * 8))
                        {
                            RestoreSignalNativeStandardOrder1(in parameters);
                        }
                        else
                        {
                            RestoreSignal64StandardOrder1(in parameters);
                        }
                        return;
                    case 2:
                        if (Unsafe.SizeOf<nint>() == sizeof(long) || (RuntimeFeature.IsDynamicCodeCompiled && parameters.MultiplyBitsRequired <= Unsafe.SizeOf<nint>() * 8 && parameters.AccumulatorBitsRequired <= Unsafe.SizeOf<nint>() * 8))
                        {
                            RestoreSignalNativeStandardOrder2(in parameters);
                        }
                        else
                        {
                            RestoreSignal64StandardOrder2(in parameters);
                        }
                        return;
                    case 3:
                        if (Unsafe.SizeOf<nint>() == sizeof(long) || (RuntimeFeature.IsDynamicCodeCompiled && parameters.MultiplyBitsRequired <= Unsafe.SizeOf<nint>() * 8 && parameters.AccumulatorBitsRequired <= Unsafe.SizeOf<nint>() * 8))
                        {
                            RestoreSignalNativeStandardOrder3(in parameters);
                        }
                        else
                        {
                            RestoreSignal64StandardOrder3(in parameters);
                        }
                        return;
                    case 4:
                        RestoreSignal64Sse41Order4(in parameters);
                        return;
                    case 5:
                        RestoreSignal64Sse41Order5(in parameters);
                        return;
                    case 6:
                        RestoreSignal64AltAvx512FVLOrder6(in parameters);
                        return;
                    case 7:
                        RestoreSignal64Sse41Order7(in parameters);
                        return;
                    case 8:
                        RestoreSignal64Avx512FVLOrder8(in parameters);
                        return;
                    case 9:
                        RestoreSignal64Avx512FVLOrder9(in parameters);
                        return;
                    case 10:
                        RestoreSignal64Avx512FVLOrder10(in parameters);
                        return;
                    case 11:
                        RestoreSignal64Avx512FVLOrder11(in parameters);
                        return;
                    case 12:
                        RestoreSignal64Avx512FVLOrder12(in parameters);
                        return;
                    case 13:
                        RestoreSignal64Avx512FVLOrder13(in parameters);
                        return;
                    case 14:
                        RestoreSignal64Avx512FVLOrder14(in parameters);
                        return;
                    case 15:
                        RestoreSignal64Avx512FVLOrder15(in parameters);
                        return;
                    case 16:
                        RestoreSignal64Avx512FVLOrder16(in parameters);
                        return;
                    case 17:
                        RestoreSignal64Avx512FVLOrder17(in parameters);
                        return;
                    case 18:
                        RestoreSignal64Avx512FVLOrder18(in parameters);
                        return;
                    case 19:
                        RestoreSignal64Avx512FVLOrder19(in parameters);
                        return;
                    case 20:
                        RestoreSignal64Avx512FVLOrder20(in parameters);
                        return;
                    case 21:
                        RestoreSignal64Avx512FVLOrder21(in parameters);
                        return;
                    case 22:
                        RestoreSignal64Avx512FVLOrder22(in parameters);
                        return;
                    case 23:
                        RestoreSignal64Avx512FVLOrder23(in parameters);
                        return;
                    case 24:
                        RestoreSignal64Avx512FVLOrder24(in parameters);
                        return;
                    case 25:
                        RestoreSignal64Avx512FVLOrder25(in parameters);
                        return;
                    case 26:
                        RestoreSignal64Avx512FVLOrder26(in parameters);
                        return;
                    case 27:
                        RestoreSignal64Avx512FVLOrder27(in parameters);
                        return;
                    case 28:
                        RestoreSignal64Avx512FVLOrder28(in parameters);
                        return;
                    case 29:
                        RestoreSignal64Avx512FVLOrder29(in parameters);
                        return;
                    case 30:
                        RestoreSignal64Avx512FVLOrder30(in parameters);
                        return;
                    case 31:
                        RestoreSignal64Avx512FVLOrder31(in parameters);
                        return;
                    case 32:
                        RestoreSignal64Avx512FVLOrder32(in parameters);
                        return;
                    default:
                        throw new FlacException("Invalid FLAC stream!");
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64AltAvx512FVLOrder6(in RestoreParameters parameters)
            {
                const int Order = 6;
                var coeffs = parameters.Coefficients;
                ArgumentOutOfRangeException.ThrowIfLessThan(coeffs.Length, Order);
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vshift = Vector128.CreateScalar((ulong)shiftsNeeded);
                var vzero = Vector128<long>.Zero;
                var vzero256 = vzero.ToVector256Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector256<long> vsum0 = default;
                int dataLength = output.Length - Order;
                Vector256<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                long nlast = 0;
                var vlast = Vector256.Create(Unsafe.Add(ref o, 0));
                vsum0 = Avx2.Multiply(vcoeff0, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector256.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx2.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.VL.AlignRight64(vzero256, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector256.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx2.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.VL.AlignRight64(vzero256, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder8(in RestoreParameters parameters)
            {
                const int Order = 8;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 0)), 2)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum0 = Avx512F.Multiply(vcoeff0, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vzero512, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vzero512, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder9(in RestoreParameters parameters)
            {
                const int Order = 9;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 1)), 1)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum0 = Avx512F.Multiply(vcoeff0, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vzero512, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vzero512, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder10(in RestoreParameters parameters)
            {
                const int Order = 10;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum0 = Avx512F.Multiply(vcoeff0, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vzero512, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vzero512, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder11(in RestoreParameters parameters)
            {
                const int Order = 11;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Vector256.CreateScalarUnsafe(Unsafe.Add(ref c, Order - 1)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder12(in RestoreParameters parameters)
            {
                const int Order = 12;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Sse41.ConvertToVector128Int64(Vector128.CreateScalarUnsafe(Unsafe.As<int, ulong>(ref Unsafe.Add(ref c, 10))).AsUInt32()).ToVector256Unsafe().AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder13(in RestoreParameters parameters)
            {
                const int Order = 13;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 9))).AsInt32();
                vcoeff1 = Avx512F.VL.AlignRight32(vzero512.GetLower().AsInt32(), vcoeff1, 2);
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder14(in RestoreParameters parameters)
            {
                const int Order = 14;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx2.Multiply(vcoeff1, vlast.GetLower()).ToVector512Unsafe();
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder15(in RestoreParameters parameters)
            {
                const int Order = 15;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 7)), 3)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx512F.Multiply(vcoeff1, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder16(in RestoreParameters parameters)
            {
                const int Order = 16;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 8)), 2)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx512F.Multiply(vcoeff1, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder17(in RestoreParameters parameters)
            {
                const int Order = 17;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 9)), 1)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx512F.Multiply(vcoeff1, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder18(in RestoreParameters parameters)
            {
                const int Order = 18;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum1 = Avx512F.Multiply(vcoeff1, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vzero512, vsum1, 1);
                    vsum1 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder19(in RestoreParameters parameters)
            {
                const int Order = 19;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Vector256.CreateScalarUnsafe(Unsafe.Add(ref c, Order - 1)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder20(in RestoreParameters parameters)
            {
                const int Order = 20;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Sse41.ConvertToVector128Int64(Vector128.CreateScalarUnsafe(Unsafe.As<int, ulong>(ref Unsafe.Add(ref c, 18))).AsUInt32()).ToVector256Unsafe().AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder21(in RestoreParameters parameters)
            {
                const int Order = 21;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 17))).AsInt32();
                vcoeff2 = Avx512F.VL.AlignRight32(vzero512.GetLower().AsInt32(), vcoeff2, 2);
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder22(in RestoreParameters parameters)
            {
                const int Order = 22;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx2.Multiply(vcoeff2, vlast.GetLower()).ToVector512Unsafe();
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder23(in RestoreParameters parameters)
            {
                const int Order = 23;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 15)), 3)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx512F.Multiply(vcoeff2, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder24(in RestoreParameters parameters)
            {
                const int Order = 24;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 16)), 2)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx512F.Multiply(vcoeff2, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder25(in RestoreParameters parameters)
            {
                const int Order = 25;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 17)), 1)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx512F.Multiply(vcoeff2, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder26(in RestoreParameters parameters)
            {
                const int Order = 26;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum2 = Avx512F.Multiply(vcoeff2, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vzero512, vsum2, 1);
                    vsum2 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder27(in RestoreParameters parameters)
            {
                const int Order = 27;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default, vsum3 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                var vcoeff3 = Vector256.CreateScalarUnsafe(Unsafe.Add(ref c, Order - 1)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum3 = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder28(in RestoreParameters parameters)
            {
                const int Order = 28;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default, vsum3 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                var vcoeff3 = Sse41.ConvertToVector128Int64(Vector128.CreateScalarUnsafe(Unsafe.As<int, ulong>(ref Unsafe.Add(ref c, 26))).AsUInt32()).ToVector256Unsafe().AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum3 = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder29(in RestoreParameters parameters)
            {
                const int Order = 29;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default, vsum3 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                var vcoeff3 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 25))).AsInt32();
                vcoeff3 = Avx512F.VL.AlignRight32(vzero512.GetLower().AsInt32(), vcoeff3, 2);
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum3 = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder30(in RestoreParameters parameters)
            {
                const int Order = 30;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default, vsum3 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                var vcoeff3 = Avx2.ConvertToVector256Int64(Unsafe.As<int, Vector128<uint>>(ref Unsafe.Add(ref c, 26))).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum3 = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx2.Multiply(vcoeff3, vlast.GetLower()).ToVector512Unsafe();
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder31(in RestoreParameters parameters)
            {
                const int Order = 31;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default, vsum3 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                var vcoeff3 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 23)), 3)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum3 = Avx512F.Multiply(vcoeff3, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx512F.Multiply(vcoeff3, vlast);
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx512F.Multiply(vcoeff3, vlast);
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal static unsafe void RestoreSignal64Avx512FVLOrder32(in RestoreParameters parameters)
            {
                const int Order = 32;
                var coeffs = parameters.Coefficients;
                ref var c = ref MemoryMarshal.GetReference(coeffs);
                _ = coeffs[Order - 1];
                var shiftsNeeded = parameters.ShiftsNeeded;
                var output = parameters.Output;
                ref var o = ref MemoryMarshal.GetReference(output);
                ref var d = ref Unsafe.Add(ref o, Order);

                var vzero = Vector128<long>.Zero;
                var vzero512 = vzero.ToVector256Unsafe().ToVector512Unsafe();
                long sum0 = 0, sum1 = 0;
                Vector512<long> vsum0 = default, vsum1 = default, vsum2 = default, vsum3 = default;
                int dataLength = output.Length - Order;
                Vector512<long> prod = default;
                long coeff0 = Unsafe.Add(ref c, 0);
                long coeff1 = Unsafe.Add(ref c, 1);
                var vcoeff0 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 2))).AsInt32();
                var vcoeff1 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 10))).AsInt32();
                var vcoeff2 = Avx512F.ConvertToVector512UInt64(Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 18))).AsInt32();
                var vcoeff3 = Avx512F.ConvertToVector512UInt64(Avx512F.VL.AlignRight32(vzero512.GetLower().AsUInt32(), Unsafe.As<int, Vector256<uint>>(ref Unsafe.Add(ref c, 24)), 2)).AsInt32();
                long nlast = 0;
                var vlast = Vector512.Create(Unsafe.Add(ref o, 0));
                vsum3 = Avx512F.Multiply(vcoeff3, vlast);
                var sum2 = vsum0.GetElement(0);
                for (var i = 1; i < Order; i++)
                {
                    nlast = Unsafe.Add(ref o, i);
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx512F.Multiply(vcoeff3, vlast);
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
                var rax = sum0 >> shiftsNeeded;
                for (nint i = 0; i < dataLength; i++)
                {
                    var res = Unsafe.Add(ref d, i);
                    rax += res;
                    nlast = rax;
                    Unsafe.Add(ref d, i) = (int)rax;
                    vlast = Vector512.Create(nlast).AsInt32();
                    sum0 = sum1 + nlast * coeff0;
                    rax = sum0 >> shiftsNeeded;
                    sum1 = sum2 + nlast * coeff1;
                    prod = Avx512F.Multiply(vcoeff0, vlast);
                    vsum0 = Avx512F.AlignRight64(vsum1, vsum0, 1);
                    vsum0 += prod;
                    sum2 = vsum0.GetElement(0);
                    prod = Avx512F.Multiply(vcoeff1, vlast);
                    vsum1 = Avx512F.AlignRight64(vsum2, vsum1, 1);
                    vsum1 += prod;
                    prod = Avx512F.Multiply(vcoeff2, vlast);
                    vsum2 = Avx512F.AlignRight64(vsum3, vsum2, 1);
                    vsum2 += prod;
                    prod = Avx512F.Multiply(vcoeff3, vlast);
                    vsum3 = Avx512F.AlignRight64(vzero512, vsum3, 1);
                    vsum3 += prod;
                }
            }
        }
    }
}