using System;

namespace Shamisen.Codecs.Native.Flac.LibFLAC
{
    public enum FLAC__StreamEncoderState
    {
        FLAC__STREAM_ENCODER_OK = 0,
        FLAC__STREAM_ENCODER_UNINITIALIZED,
        FLAC__STREAM_ENCODER_OGG_ERROR,
        FLAC__STREAM_ENCODER_VERIFY_DECODER_ERROR,
        FLAC__STREAM_ENCODER_VERIFY_MISMATCH_IN_AUDIO_DATA,
        FLAC__STREAM_ENCODER_CLIENT_ERROR,
        FLAC__STREAM_ENCODER_IO_ERROR,
        FLAC__STREAM_ENCODER_FRAMING_ERROR,
        FLAC__STREAM_ENCODER_MEMORY_ALLOCATION_ERROR,
    }
}
