using System;

namespace Shamisen.Codecs.Native.Flac.LibFLAC
{
    public enum FLAC__Metadata_ChainStatus
    {
        FLAC__METADATA_CHAIN_STATUS_OK = 0,
        FLAC__METADATA_CHAIN_STATUS_ILLEGAL_INPUT,
        FLAC__METADATA_CHAIN_STATUS_ERROR_OPENING_FILE,
        FLAC__METADATA_CHAIN_STATUS_NOT_A_FLAC_FILE,
        FLAC__METADATA_CHAIN_STATUS_NOT_WRITABLE,
        FLAC__METADATA_CHAIN_STATUS_BAD_METADATA,
        FLAC__METADATA_CHAIN_STATUS_READ_ERROR,
        FLAC__METADATA_CHAIN_STATUS_SEEK_ERROR,
        FLAC__METADATA_CHAIN_STATUS_WRITE_ERROR,
        FLAC__METADATA_CHAIN_STATUS_RENAME_ERROR,
        FLAC__METADATA_CHAIN_STATUS_UNLINK_ERROR,
        FLAC__METADATA_CHAIN_STATUS_MEMORY_ALLOCATION_ERROR,
        FLAC__METADATA_CHAIN_STATUS_INTERNAL_ERROR,
        FLAC__METADATA_CHAIN_STATUS_INVALID_CALLBACKS,
        FLAC__METADATA_CHAIN_STATUS_READ_WRITE_MISMATCH,
        FLAC__METADATA_CHAIN_STATUS_WRONG_WRITE_CALL,
    }
}
