using System;

namespace Shamisen.Codecs.Native.Flac.LibFLAC
{
    public enum FLAC__Metadata_SimpleIteratorStatus
    {
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_OK = 0,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_ILLEGAL_INPUT,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_ERROR_OPENING_FILE,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_NOT_A_FLAC_FILE,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_NOT_WRITABLE,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_BAD_METADATA,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_READ_ERROR,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_SEEK_ERROR,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_WRITE_ERROR,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_RENAME_ERROR,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_UNLINK_ERROR,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_MEMORY_ALLOCATION_ERROR,
        FLAC__METADATA_SIMPLE_ITERATOR_STATUS_INTERNAL_ERROR,
    }
}
