using System;

namespace Shamisen.Codecs.Native.Flac.LibFLAC
{
    public enum FLAC__StreamEncoderInitStatus
    {
        FLAC__STREAM_ENCODER_INIT_STATUS_OK = 0,
        FLAC__STREAM_ENCODER_INIT_STATUS_ENCODER_ERROR,
        FLAC__STREAM_ENCODER_INIT_STATUS_UNSUPPORTED_CONTAINER,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_CALLBACKS,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_NUMBER_OF_CHANNELS,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_BITS_PER_SAMPLE,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_SAMPLE_RATE,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_BLOCK_SIZE,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_MAX_LPC_ORDER,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_QLP_COEFF_PRECISION,
        FLAC__STREAM_ENCODER_INIT_STATUS_BLOCK_SIZE_TOO_SMALL_FOR_LPC_ORDER,
        FLAC__STREAM_ENCODER_INIT_STATUS_NOT_STREAMABLE,
        FLAC__STREAM_ENCODER_INIT_STATUS_INVALID_METADATA,
        FLAC__STREAM_ENCODER_INIT_STATUS_ALREADY_INITIALIZED,
    }
}
