using System;

namespace Shamisen.Codecs.Native.Flac.LibFLAC
{
    public enum FLAC__StreamMetadata_Picture_Type
    {
        FLAC__STREAM_METADATA_PICTURE_TYPE_OTHER = 0,
        FLAC__STREAM_METADATA_PICTURE_TYPE_FILE_ICON_STANDARD = 1,
        FLAC__STREAM_METADATA_PICTURE_TYPE_FILE_ICON = 2,
        FLAC__STREAM_METADATA_PICTURE_TYPE_FRONT_COVER = 3,
        FLAC__STREAM_METADATA_PICTURE_TYPE_BACK_COVER = 4,
        FLAC__STREAM_METADATA_PICTURE_TYPE_LEAFLET_PAGE = 5,
        FLAC__STREAM_METADATA_PICTURE_TYPE_MEDIA = 6,
        FLAC__STREAM_METADATA_PICTURE_TYPE_LEAD_ARTIST = 7,
        FLAC__STREAM_METADATA_PICTURE_TYPE_ARTIST = 8,
        FLAC__STREAM_METADATA_PICTURE_TYPE_CONDUCTOR = 9,
        FLAC__STREAM_METADATA_PICTURE_TYPE_BAND = 10,
        FLAC__STREAM_METADATA_PICTURE_TYPE_COMPOSER = 11,
        FLAC__STREAM_METADATA_PICTURE_TYPE_LYRICIST = 12,
        FLAC__STREAM_METADATA_PICTURE_TYPE_RECORDING_LOCATION = 13,
        FLAC__STREAM_METADATA_PICTURE_TYPE_DURING_RECORDING = 14,
        FLAC__STREAM_METADATA_PICTURE_TYPE_DURING_PERFORMANCE = 15,
        FLAC__STREAM_METADATA_PICTURE_TYPE_VIDEO_SCREEN_CAPTURE = 16,
        FLAC__STREAM_METADATA_PICTURE_TYPE_FISH = 17,
        FLAC__STREAM_METADATA_PICTURE_TYPE_ILLUSTRATION = 18,
        FLAC__STREAM_METADATA_PICTURE_TYPE_BAND_LOGOTYPE = 19,
        FLAC__STREAM_METADATA_PICTURE_TYPE_PUBLISHER_LOGOTYPE = 20,
        FLAC__STREAM_METADATA_PICTURE_TYPE_UNDEFINED,
    }
}
