using System;

namespace Shamisen.Codecs.Native.Flac.LibFLAC
{
    public enum FLAC__StreamDecoderInitStatus
    {
        FLAC__STREAM_DECODER_INIT_STATUS_OK = 0,
        FLAC__STREAM_DECODER_INIT_STATUS_UNSUPPORTED_CONTAINER,
        FLAC__STREAM_DECODER_INIT_STATUS_INVALID_CALLBACKS,
        FLAC__STREAM_DECODER_INIT_STATUS_MEMORY_ALLOCATION_ERROR,
        FLAC__STREAM_DECODER_INIT_STATUS_ERROR_OPENING_FILE,
        FLAC__STREAM_DECODER_INIT_STATUS_ALREADY_INITIALIZED,
    }
}
