// <auto-generated />
using System;
using System.Collections.Generic;

using NUnit.Framework;

using Shamisen.Codecs.Flac.SubFrames;

namespace Shamisen.Core.Tests.CoreFx.Codecs.Flac
{
    [TestFixture]
    public partial class FlacLinearPredictionSubFrameRestoreTests
    {

        [TestCaseSource(nameof(RestoreSignalTestCaseSource))]
        public void RestoreSignalSse41RestoresCorrectly(int order, int shiftsNeeded, int bitsPerSample, int quantizedPrecision, int outputLength)
        {
            if (!FlacLinearPredictionSubFrame.X86.IsSse41Supported) Assert.Ignore("Sse41 is not supported!");
            var data = new TestData(order, shiftsNeeded, bitsPerSample, quantizedPrecision, outputLength);
            var outputBuffer = new int[outputLength + order];
            data.WarmupSignal.CopyTo(outputBuffer);
            data.Residuals.CopyTo(outputBuffer.AsSpan(data.Order));
            FlacLinearPredictionSubFrame.X86.RestoreSignalSse41(data.GenerateParameters(outputBuffer));
            Assert.That(outputBuffer, Is.EqualTo(data.ExpectedOutput));
        }

        [TestCaseSource(nameof(RestoreSignalTestCaseSource))]
        public void RestoreSignalAvx2RestoresCorrectly(int order, int shiftsNeeded, int bitsPerSample, int quantizedPrecision, int outputLength)
        {
            if (!FlacLinearPredictionSubFrame.X86.IsAvx2Supported) Assert.Ignore("Avx2 is not supported!");
            var data = new TestData(order, shiftsNeeded, bitsPerSample, quantizedPrecision, outputLength);
            var outputBuffer = new int[outputLength + order];
            data.WarmupSignal.CopyTo(outputBuffer);
            data.Residuals.CopyTo(outputBuffer.AsSpan(data.Order));
            FlacLinearPredictionSubFrame.X86.RestoreSignalAvx2(data.GenerateParameters(outputBuffer), true);
            Assert.That(outputBuffer, Is.EqualTo(data.ExpectedOutput));
        }

        [TestCaseSource(nameof(RestoreSignalTestCaseSource))]
        public void RestoreSignalAvx512FVLRestoresCorrectly(int order, int shiftsNeeded, int bitsPerSample, int quantizedPrecision, int outputLength)
        {
            if (!FlacLinearPredictionSubFrame.X86.IsAvx512FVLSupported) Assert.Ignore("Avx512FVL is not supported!");
            var data = new TestData(order, shiftsNeeded, bitsPerSample, quantizedPrecision, outputLength);
            var outputBuffer = new int[outputLength + order];
            data.WarmupSignal.CopyTo(outputBuffer);
            data.Residuals.CopyTo(outputBuffer.AsSpan(data.Order));
            FlacLinearPredictionSubFrame.X86.RestoreSignalAvx512FVL(data.GenerateParameters(outputBuffer));
            Assert.That(outputBuffer, Is.EqualTo(data.ExpectedOutput));
        }
    }
}