name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        include-prerelease: true
    - name: Build
      run: dotnet build ./Tests/Shamisen.Core.Tests.CoreFx/Shamisen.Core.Tests.CoreFx.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Tests/Shamisen.Core.Tests.CoreFx/Shamisen.Core.Tests.CoreFx.csproj
