<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ShamisenCurrentTargetFramework)</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == '$(ShamisenCurrentTargetFramework)'">
        <!--<EnablePreviewFeatures>true</EnablePreviewFeatures>-->
    </PropertyGroup>
    <PropertyGroup>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugType>pdbonly</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <Import Project="../T4Transform.targets" />
    <ItemGroup>
        <None Remove="TestSounds\PinkNoise_24bit_Lv8.flac" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="TestSounds\PinkNoise_24bit_Lv8.flac" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.6" />
        <PackageReference Include="CSCore" Version="1.2.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Codecs\Managed\Shamisen.Codecs.Flac\Shamisen.Codecs.Flac.csproj" />
        <ProjectReference Include="..\Shamisen\Shamisen.csproj" />
    </ItemGroup>
</Project>